a= int(input("enter number 1: "))
b= int(input("enter number 2: "))

print("Addition")
print("a+b=",a+b)
print()
print("Subtraction")
print("a-b=", a-b)
print()
print("Multiplication")
print("a*b=", a*b)
print()
print("Division")
print("a/b=", a/b)
print()
print("Modulus")
print("a%b=", a%b)
print()
print("Exponent")
print("a**b=", a**b)
print()
print("Floor Division")
print("a//b=", a//b)
print()
